name: Timetable CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: mad-maids/maid.table
          path: new-timetable
      - run: |
          ls -la
          ls new-timetable
#          rm -rf timetable
#          mv new-timetable timetable
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#          git add .
