name: Timetable CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      with:
        repository: mad-maids/maid.table
        path: timetable
      -run: |
        ls -la