name: Timetable CI

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: mad-maids/maid.table
          path: new-timetable
      - run: |
          rm -rf timetable
          mv new-timetable/data timetable
          rm -rf new-timetable
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          [[ -z $(git status -uno --porcelain) ]] && echo "this branch is clean, no need to push..." && exit 0;
          git commit -m "Updated timetable"
          git push
