name: Timetable CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: mad-maids/maid.table
          path: new-timetable
      - run: |
          ls -la