name: Timetable CI

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Update data to the latest commit
        run: |
          git submodule foreach '
            git fetch origin main;
            git checkout main;
            git pull origin main;
          '

      - name: Push changes to the main repo
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          [[ -z $(git status -uno --porcelain) ]] && echo "No updates detected, no need for push" && exit 0;
          git commit -m "update timetable $(date -u)"
          git push origin main --force